name: Run tests
on:
  push:
    branches: main
  pull_request:
  workflow_call:

jobs:
  build-and-test-32bit:
    name: Build & test - x86
    runs-on: windows-2022
    permissions: {}
    steps:
      - name: Log installed Windows SDK versions
        shell: pwsh
        continue-on-error: true
        run: Get-ChildItem -Name "HKLM:\SOFTWARE\Microsoft\Windows Kits\Installed Roots"

      - name: Log active MSVC compiler version
        shell: pwsh
        continue-on-error: true
        run: |
          $installDir = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          $path = Join-Path $installDir 'VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt'
          $version = Get-Content -raw $path
          $clPath = Join-Path $installDir "VC\Tools\MSVC\$($version.Trim())\bin\Hostx64\x64\cl.exe"
          & $clPath

      - name: Add MSBuild to the PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57  # v3

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all the history so that `git describe` works to generate the version header
          fetch-tags: true

      - name: Build debug binaries
        run: msbuild /r /m /p:Configuration=Debug /p:Platform=x86 build\foo_openlyrics.sln

      - name: Run tests
        run: build\Debug\test_foo_openlyrics.exe build\Debug\foo_openlyrics.dll

      - name: Build release binaries
        run: msbuild /r /m /p:Configuration=Release /p:Platform=x86 build\foo_openlyrics.sln

  build-and-test-64bit:
    name: Build & test - x64
    runs-on: windows-2022
    permissions: {}
    steps:
      - name: Add MSBuild to the PATH
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57  # v3

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all the history so that `git describe` works to generate the version header
          fetch-tags: true

      - name: Build debug binaries
        run: msbuild /r /m /p:Configuration=Debug /p:Platform=x64 build\foo_openlyrics.sln

      - name: Run tests
        run: build\x64\Debug\test_foo_openlyrics.exe build\x64\Debug\foo_openlyrics.dll

      - name: Build release binaries
        run: msbuild /r /m /p:Configuration=Release /p:Platform=x64 build\foo_openlyrics.sln

  build-and-test-arm64:
    name: Build & test - ARM64
    runs-on: windows-11-arm
    permissions: {}
    steps:
      - name: Add MSBuild to the PATH
        uses: microsoft/setup-msbuild@v3

      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all the history so that `git describe` works to generate the version header
          fetch-tags: true

      - name: Build debug binaries
        run: msbuild /r /m /p:Configuration=Debug /p:Platform=ARM64 build\foo_openlyrics.sln

      - name: Run tests
        run: build\ARM64\Debug\test_foo_openlyrics.exe build\ARM64\Debug\foo_openlyrics.dll

      - name: Build release binaries
        run: msbuild /r /m /p:Configuration=Release /p:Platform=ARM64 build\foo_openlyrics.sln
